# Hibernate manages schema in dev no need for Flyway
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false

# Show and format SQL queries in console for easier debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator show full health details locally
management.endpoint.health.show-details=always

# Swagger enabled in dev
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true



# Stripe CLI forwards webhooks locally and gives a temporary whsec_ override here
# stripe listen --forward-to localhost:8083/api/v1/payments/webhook
# stripe.webhook-secret=whsec_<from_stripe_listen_output>
